Add category model
denysokhrymovych/book-shop pull request #10
Opened 2024-01-04 07:21 UTC by denysokhrymovych

2024-01-05 07:15 UTC, DPotapov93 approved these changes
Good job!

2024-01-05 10:28 UTC, d1sam requested changes
good job, but there are some minor changes should be done!

2024-01-05 10:28 UTC, d1sam commented on src/main/java/com/example/bookshop/controller/CategoryController.java
> +    @PostMapping
```suggestion
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED) 
```

2024-01-05 10:28 UTC, d1sam commented on src/main/java/com/example/bookshop/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ADMIN')")
```

2024-01-05 10:28 UTC, d1sam commented on src/main/java/com/example/bookshop/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ADMIN')")
```

2024-01-05 10:28 UTC, d1sam commented on src/main/java/com/example/bookshop/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ADMIN')")
```

2024-01-05 10:28 UTC, d1sam commented on src/main/java/com/example/bookshop/model/Category.java
> +    private String description;
```suggestion
    @Column
    private String description;
```

2024-01-08 13:38 UTC, vovasalyha approved these changes

2024-01-15 11:55 UTC, merged