Add shoppingcart model
denysokhrymovych/book-shop pull request #11
Opened 2024-01-15 11:57 UTC by denysokhrymovych

2024-01-17 07:05 UTC, yevheniisynytsia requested changes
Well done!
Left some comments to work on =)

2024-01-17 07:05 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/dto/cart/AddToCartRequestDto.java
> +    private int quantity;
please add `@NotNull` as well

2024-01-17 07:05 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/dto/cart/UpdateCartItemRequestDto.java
> +    @Positive(message = "Quantity must be greater than 0")
same

2024-01-17 07:05 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/model/CartItem.java
> +    @ManyToOne
please avoid using `FetchType.EAGER`

2024-01-17 07:05 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/model/CartItem.java
> +    @ManyToOne
please avoid using `FetchType.EAGER`

2024-01-17 07:05 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/model/ShoppingCart.java
> +    @OneToOne
please avoid using `FetchType.EAGER`

2024-01-18 09:05 UTC, d1sam requested changes
some mistakes still exist.

2024-01-18 09:05 UTC, d1sam commented on src/main/java/com/example/bookshop/dto/cart/AddToCartRequestDto.java
> +    private int quantity;
still exist

2024-01-18 09:05 UTC, d1sam commented on src/main/java/com/example/bookshop/dto/cart/UpdateCartItemRequestDto.java
> +    @Positive(message = "Quantity must be greater than 0")
add `@NotNull`

2024-01-18 09:05 UTC, d1sam commented on src/main/java/com/example/bookshop/service/shoppingcart/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto addToCart(AddToCartRequestDto requestDto, Long userId) {
split to smaller private methods

2024-01-18 09:05 UTC, d1sam commented on src/main/java/com/example/bookshop/service/shoppingcart/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Transactional
    @Override
```

2024-01-18 10:39 UTC, yevheniisynytsia approved these changes
well done!

2024-01-18 10:39 UTC, yevheniisynytsia commented on src/main/java/com/example/bookshop/dto/cart/AddToCartRequestDto.java
> +    private int quantity;
my bad

@denysokhrymovych good catch about primitives and null values!

2024-01-18 11:01 UTC, merged