Spring boot security
denysokhrymovych/book-shop pull request #7
Opened 2023-12-20 16:11 UTC by denysokhrymovych

add required DTOs and mapper,
add AuthController,
add FieldMatch annotation,
handle the RegistrationException using the GlobalExceptionHandler

2023-12-21 07:33 UTC, bhdnchui requested changes
Good job! Just a few points to consider.

2023-12-21 07:33 UTC, bhdnchui commented on src/main/java/com/example/bookshop/dto/user/UserRegistrationRequestDto.java
> +    @NotNull(message = "First name cannot be null")
Let's use `@NotBlank` for better validation

2023-12-21 07:33 UTC, bhdnchui commented on src/main/java/com/example/bookshop/dto/user/UserRegistrationRequestDto.java
> +    @NotNull(message = "Last name cannot be null")
Let's use `@NotBlank` for better validation

2023-12-21 07:33 UTC, bhdnchui commented on src/main/java/com/example/bookshop/dto/user/UserRegistrationRequestDto.java
> +    private String repeatPassword;
Add constraints for these fields.

2023-12-21 07:33 UTC, bhdnchui commented on src/main/java/com/example/bookshop/validation/PasswordMatchesValidator.java
> +        UserRegistrationRequestDto userDto = (UserRegistrationRequestDto) obj;
Let's avoid class casting.

2023-12-21 07:33 UTC, bhdnchui commented on src/main/java/com/example/bookshop/validation/PasswordMatchesValidator.java
> +        return userDto.getPassword().equals(userDto.getRepeatPassword());
Let's compare passwords with Objects#equals

2023-12-21 07:33 UTC, bhdnchui commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(exceptionDto, HttpStatus.BAD_REQUEST);
Why do you return ExceptionDto dto here, if you return LinkedHashMap in handleEntityNotFoundException method.
Be consistent. Let's reuse code from handleEntityNotFoundException method to handle RegistrationException

2023-12-22 08:55 UTC, bhdnchui requested changes
Just one point to fix.

2023-12-22 08:55 UTC, bhdnchui commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.BAD_REQUEST);
This code is pretty equal to handleEntityNotFoundException method body. 
Please, avoid code duplication.

2023-12-26 07:32 UTC, d1sam requested changes
Some changes should be done according to me comment

2023-12-26 07:32 UTC, d1sam commented on src/main/java/com/example/bookshop/config/SecurityConfig.java
You don't need to add SecurityConfig in this hw

2023-12-26 07:32 UTC, d1sam commented on src/main/java/com/example/bookshop/model/Role.java
you don't need to add role in this homework

2023-12-26 07:32 UTC, d1sam commented on src/main/java/com/example/bookshop/validation/FieldMatch.java
> +public @interface FieldMatch {
```suggestion
public @interface PasswordsFieldsMatch {
```

2023-12-26 07:32 UTC, d1sam commented on src/main/java/com/example/bookshop/validation/FieldMatch.java
> +public @interface FieldMatch {
because you check only passwords in your `FieldMatchValidator`

2023-12-26 07:32 UTC, d1sam commented on src/main/java/com/example/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 07:32 UTC, d1sam commented on src/main/java/com/example/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 07:32 UTC, d1sam commented on src/main/java/com/example/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-27 07:44 UTC, d1sam approved these changes
Well done!

2023-12-27 12:58 UTC, merged